### ISSUE TITLE
Add Code Comments

### ISSUE THREAD

**Issue by tracyarciaga** [0xRS/halo-rewards#11]
Add comments on critical areas of the code, to help us better understand (e.g. calcReward(), updateMinterRewardPool(), updateAmmRewardPool()).

**Comment by ernestpascual** [comment]
also good to add some sort of general flow on how things are happening. for example:
https://github.com/sushiswap/sushiswap/blob/ad72898483b4c49803291bd09a2737e4e5dbed16/contracts/MasterChef.sol#L40

https://github.com/UMAprotocol/protocol/blob/684f78f09e284466fac74c7388cab56d56aadd4c/packages/core/contracts/financial-templates/demo/DepositBox.sol#L31

Thanks!
