### ISSUE TITLE
Implement Vesting

### ISSUE THREAD

**Issue by tracyarciaga** [0xRS/halo-rewards#6]
Refer to this section of the rewards contract specs.
(https://docs.google.com/document/d/1xF8kiopKTd_KLhmJtAB_H6KpLeqo1_QDw6F11Bb0uQQ/edit?disco=AAAAH9UK7yA)

**Comment by 0xrs** [comment]
Current implementation of vesting is in the vesting branch. Differs from old specs as discussed.
